---

- hosts: admin_server
    

  vars_files:
    - vars/common.yml
    - vars/{{ ENV }}/tibco{{ VARIANT }}.yml 



  tasks:

    - name: Start CachePU
      shell:
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(CACHE_PU[0].host)][0].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/BE Engine {{ PU['%s' | format(CACHE_PU[0].host)][0].pu_name }} started/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash
           
      loop: "{{ CACHE_PU }}"
      register: stdout
      when: CACHE_PU is defined
      tags: CACHE_PU
    - debug: var=stdout



    - name: Start ABSServicePU
      shell:
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(ABSSERVICE_PU[0].host)][0].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ ABSSERVICE_PU[0].host }}(.*?)\.{{ PU['%s' | format(ABSSERVICE_PU[0].host)][0].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args:
        executable: /bin/bash

      loop: "{{ ABSSERVICE_PU }}"
      register: stdout
      when: ABSSERVICE_PU is defined
      tags: ABSSERVICE_PU
    - debug: var=stdout



    - name: Start AuditPU
      shell: 
        cmd: | 
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(AUDIT_PU[0].host)][1].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ AUDIT_PU[0].host }}(.*?)\.{{ PU['%s' | format(AUDIT_PU[0].host)][1].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash

      loop: "{{ AUDIT_PU }}"
      register: stdout 
      when: AUDIT_PU is defined
      tags: AUDIT_PU
    - debug: var=stdout



    - name: Start HeartBeatPU
      shell: 
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(HEARTBEAT_PU[0].host)][0].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ HEARTBEAT_PU[0].host }}(.*?)\.{{ PU['%s' | format(HEARTBEAT_PU[0].host)][0].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash

      loop: "{{ HEARTBEAT_PU }}"
      register: stdout 
      when: HEARTBEAT_PU is defined
      tags: HEARTBEAT_PU
    - debug: var=stdout



    - name: Start BillingProcPU
      shell: 
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(BILLING_PROC_PU[0].host)][2].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ BILLING_PROC_PU[0].host }}(.*?)\.{{ PU['%s' | format(BILLING_PROC_PU[0].host)][2].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash

      loop: "{{ BILLING_PROC_PU }}"
      register: stdout 
      when: BILLING_PROC_PU is defined
      tags: BILLING_PROC_PU
    - debug: var=stdout



    - name: Start SymWalletPU
      shell: 
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(SYMWALLET_PU[0].host)][1].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ SYMWALLET_PU[0].host }}(.*?)\.{{ PU['%s' | format(SYMWALLET_PU[0].host)][1].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash    

      loop: "{{ SYMWALLET_PU }}"
      register: stdout 
      when: SYMWALLET_PU is defined
      tags: SYMWALLET_PU
    - debug: var=stdout

      

    - name: Start EComCloudPU
      shell: 
        cmd: |
          cd {{ BE_PATH }} && ./{{ item.start }} && {{ REMOTE_CMD }} {{ item.host }} <<'EOF'
            perl -w <<'PERL'
            use strict;
            use warnings;
            my $pid;
            eval {
              local $SIG{ALRM} = sub { kill 15, $pid; die "TIMEDOUT!" };
              alarm {{ MAX_TIMEOUT_SECS }};
              $pid = open(TAIL, "{{ TAIL_CMD }} {{ TIBCO_LOGS_DIR }}/{{ PU['%s' | format(ECOMCLOUD_PU[0].host)][2].pu_name }}.log |") or die "Can't open TAIL!";
              while (<TAIL>) {
                chomp;
                if (/Member: {{ ECOMCLOUD_PU[0].host }}(.*?)\.{{ PU['%s' | format(ECOMCLOUD_PU[0].host)][2].pu_name }}(.*?)Status: ACTIVATED/) {
                  print("!!! FOUND MATCH : $_ !!!\n");
                  last;
                }
              }
              kill 15, $pid; alarm 0;
            };
            if ($@) {
              die if $@ !~ /TIMEDOUT!/;  
              die "TIMEDOUT waiting for TAIL!";
            }
            exit(0);
          PERL
          EOF

      args: 
        executable: /bin/bash    

      loop: "{{ ECOMCLOUD_PU }}"
      register: stdout 
      when: ECOMCLOUD_PU is defined
      tags: ECOMCLOUD_PU
    - debug: var=stdout


